### ISSUE TITLE
Scheme Editorial Note Addition

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#90]
In metadata for all schemes, ac and pc wise, the last two rows ie methodology and remarks should be reflected as well in the scheme editorial note.

**Comment by aashimgarg** [comment]
Fixed!

**Comment by samwhocodes** [comment]
<img width="974" alt="Screenshot 2023-02-24 at 2 21 02 PM" src="https://user-images.githubusercontent.com/67921422/221134685-47b034f2-499d-4a62-b9f8-ffe5a9d3ad4c.png">
 Still not showing
