### ISSUE TITLE
The (sc) and (st) should be in uppercase 

### ISSUE THREAD

**Issue by samwhocodes** [cbgaindia/constituency-frontend#91]
<img width="924" alt="Screenshot 2023-02-23 at 10 27 39 PM" src="https://user-images.githubusercontent.com/67921422/220981680-22af349f-c541-45ac-a880-25556201ed2f.png">

**Comment by aashimgarg** [comment]
Fixed!

**Comment by samwhocodes** [comment]
Still showing these two 
![Uploading Screenshot 2023-02-24 at 2.25.31 PM.png…]()
places

**Comment by samwhocodes** [comment]
![Uploading Screenshot 2023-02-24 at 2.25.58 PM.png…]()

**Comment by samwhocodes** [comment]
<img width="640" alt="Screenshot 2023-02-24 at 2 25 31 PM" src="https://user-images.githubusercontent.com/67921422/221135878-9b6c970e-3115-4730-b89e-75036a2a6851.png">

**Comment by samwhocodes** [comment]
<img width="907" alt="Screenshot 2023-02-24 at 2 25 58 PM" src="https://user-images.githubusercontent.com/67921422/221135946-102fea16-9288-40ec-8c4e-e9ace4a4d2db.png">

Still showing in the Map view and state entry point

**Comment by aashimgarg** [comment]
I will notify Tauseef to pull the changes, and then all the updates will be reflected. @samwhocodes
